# Generated by Django 4.1.5 on 2023-01-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('inc_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('cost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_choice', models.CharField(choices=[('RENT', 'Rent'), ('DEBT', 'Debt'), ('SUBS', 'Subscriptions')], max_length=200, verbose_name='Payment')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Paid?')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving', models.FloatField(verbose_name='Saving Amount:')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_choice', models.CharField(choices=[('WATBILL', 'Water Bill'), ('ElECBILL', 'Electricity Bill')], max_length=200, verbose_name='Payment')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Paid?')),
            ],
        ),
    ]
